Fixed issue #11: compiling bug in corrcal_funs.c
corrcal_funs.c contains a print statement on line 123

  //printf("%d", creal(gains));

When compiling this corrcal library using

gcc-4.8 -fopenmp -std=c99 -O3 -shared -fPIC -o libcorrcal_funs.so corrcal_funs.c -lm -lgomp

You get the following error output

corrcal_funs.c: In function ‘apply_gains_to_mat’:
corrcal_funs.c:123:3: error: incompatible type for argument 1 of ‘creal’
   printf("%d", creal(gains));
   ^
In file included from corrcal_funs.c:7:0:
/usr/include/x86_64-linux-gnu/bits/cmathcalls.h:130:1: note: expected ‘complex double’ but argument is of type ‘_Complex double *’
 __MATHDECL (_Mdouble_,creal, (_Mdouble_complex_ __z));
 ^

Although, I haven't solved the underlying problem where it seems that variables might be passed
along incorrectly "*" instead of "&", by commenting out that line the code can compile again.